create table tb_worker (id int8 generated by default as identity, daily_income float8 not null, name varchar(255), primary key (id));
INSERT INTO tb_worker (name, daily_Income) VALUES ('Bob', 200.0);
INSERT INTO tb_worker (name, daily_Income) VALUES ('Maria', 300.0);
INSERT INTO tb_worker (name, daily_Income) VALUES ('Alex', 250.0);
INSERT INTO tb_worker (name, daily_Income) VALUES ('João', 400.0);
